---
# This file contains only configs which differ from defaults.
# All possible options can be found here
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 10s
  concurrency: 4
  tests: false
  skip-dirs:
    - api/m3uetcpb

linters-settings:
  cyclop:
    max-complexity: 30
    package-average: 10.0
    skip-tests: true

  errcheck:
    check-type-assertions: false
    check-blank: false

  godot:
    exclude:
      # Exclude commented imports
      - "^ \""

      # Exclude todo-like comments.
      - "^ BUG:"
      - "^ CHANGED:"
      - "^ FIXME:"
      - "^ HACK:"
      - "^ IDEA:"
      - "^ INFO:"
      - "^ NOTE:"
      - "^ REVIEW:"
      - "^ TRICKY:"
      - "^ TODO:"
      - "^ XXX:"

  gosimple:
    checks:
      - all
      - '-S1000'
      - '-S1038'

  govet:
    check-shadowing: false
    # Run `go tool vet help` to see all analyzers.
    disable:
      - fieldalignment
      - stdmethods

  nolintlint:
    require-explanation: true
    require-specific: true

  revive:
    rules:
      - name: package-comments
        disabled: true
    # severity: warning
    confidence: 0.8

  staticcheck:
    checks:
      - all
      # - '-SA1019' # deprecations

linters:
  disable-all: true
  enable:
    ## enabled by default
    # - errcheck # too annoying, ignores settings above
    - gosimple
    - govet
    # - ineffassign # many false positives
    - staticcheck
    - typecheck
    - unused

    ## disabled by default
    - bodyclose
    # - cyclop
    - godot
    - misspell
    - nolintlint
    - revive
    - unconvert

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
