# https://taskfile.dev

---
version: '3'

vars:
  RACE_FLAG: ''

tasks:
  ## prod build commands
  build:
    desc: Build for production
    deps: [clean]
    cmds:
      - task: build:server
      - task: build:task
      - task: build:gtk
  build:server:
    desc: Build server for production
    aliases:
      - build:s
    deps: [build:discover]
    cmds:
      - task: build:go
        vars: {SUFFIX: server}
    silent: true
  build:task:
    desc: Build task for production
    aliases:
      - build:t
    cmds:
      - task: build:go
        vars: {SUFFIX: task}
    silent: true
  build:gtk:
    desc: Build gtk for production
    aliases:
      - build:g
    deps: [copy-cmd-data]
    cmds:
      - defer: {task: remove-cmd-data}
      - task: build:go
        vars: {SUFFIX: gtk}
    silent: true
  build:discover:
    interna: true
    cmds:
      - task: build:go
        vars: {SUFFIX: discover}
  build:go:
    internal: true
    cmds:
      - >
        go build -ldflags='-s -w' -gcflags=-l -trimpath
        -o ./m3uetc-{{.SUFFIX}}{{exeExt}} ./cmd/m3uetc-{{.SUFFIX}}

  ## dev build commands

  dev:
    desc: Build for development
    cmds:
      - task: dev:server
      - task: dev:task
      - task: dev:gtk
  dev:server:
    desc: Build server for development
    aliases:
      - dev:s
    deps: [dev:discover]
    cmds:
      - task: dev:go
        vars: {SUFFIX: server, RACE_FLAG: "{{.RACE_FLAG}}"}
    silent: true
  dev:task:
    desc: Build task for development
    aliases:
      - dev:t
    cmds:
      - task: dev:go
        vars: {SUFFIX: task, RACE_FLAG: "{{.RACE_FLAG}}"}
    silent: true
  dev:gtk:
    desc: Build gtk for development
    deps: [copy-cmd-data]
    aliases:
      - dev:g
    cmds:
      - defer: {task: remove-cmd-data}
      - task: dev:go
        vars: {SUFFIX: gtk, RACE_FLAG: "{{.RACE_FLAG}}"}
    silent: true
  dev:discover:
    interna: true
    cmds:
      - task: dev:go
        vars: {SUFFIX: discover}
  dev:go:
    internal: true
    cmds:
      - >
        go build -v {{.RACE_FLAG}} -o ./m3uetc-{{.SUFFIX}}{{exeExt}}
        ./cmd/m3uetc-{{.SUFFIX}}

  ## race dev build commands

  race:
    cmds:
      - task: race:server
      - task: race:task
      - task: race:gtk
  race:server:
    aliases:
      - race:s
    cmds:
      - task: dev:server
        vars: {RACE_FLAG: '-race'}
    silent: true
  race:task:
    aliases:
      - race:t
    cmds:
      - task: dev:task
        vars: {RACE_FLAG: '-race'}
    silent: true
  race:gtk:
    aliases:
      - race:g
    cmds:
      - task: dev:gtk
        vars: {RACE_FLAG: '-race'}
    silent: true

  ## build packages

  deb:build:
    desc: Build deb package
    deps: [clean]
    cmds:
      - task: build
      - task: deb
  deb:dev:
    desc: Build deb package with dev flags
    deps: [clean]
    cmds:
      - task: dev
      - task: deb
  deb:
    internal: true
    cmds:
      - mkdir -p {{.DebPath}}/{DEBIAN,usr/local/{bin,libexec/{{.PkgName}},share/{applications,icons}}}
      - cp ./m3uetc-server ./m3uetc-task ./m3uetc-gtk {{.DebPath}}/usr/local/bin
      - cp ./m3uetc-discover {{.DebPath}}/usr/local/libexec/{{.PkgName}}/discover
      - cp ./data/m3uetc-*.desktop {{.DebPath}}/usr/local/share/applications
      - cp ./build/package/deb/control.tpl {{.DebPath}}/DEBIAN/control
      - |
        set -e
        cd ./data/images
        cp --parents scalable/m3u-etcetera.svg {{.DebPath}}/usr/local/share/icons
        for f in */m3u-etcetera.png
        do
          cp --parents $f {{.DebPath}}/usr/local/share/icons
        done
      - cd {{.DebDir}} && dpkg-deb --build {{ .PkgName }}
      - mv {{.DebDir}}/{{.PkgName}}.deb ./build
      - rm -rf {{.DebDir}} > /dev/null 2>&1 || exit 0
    vars:
      PkgName: m3u-etcetera
      DebDir:
        sh: echo $(mktemp -d /tmp/m3uetc-build-deb-XXXXXX)
      DebPath:
        sh: echo {{.DebDir}}/{{.PkgName}}

  ## semantic version commands

  bump:minor:
    desc: Bump minor version number
    aliases:
      - bump:min
    deps: [bumpy-exists]
    cmds:
      - bumpy bump --minor
  bump:patch:
    desc: Bump patch version number
    deps: [bumpy-exists]
    aliases:
      - bump:p
    cmds:
      - bumpy bump --patch
  tag:
    desc: Create tag for the current ChangeLog
    cmds:
      - bumpy tag

  ## protobuf commands

  proto:
    desc: Process protobuf files
    cmds:
      - >
        protoc --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        api/m3uetcpb/*.proto

  ## utility commands

  clean:
    desc: Clean, remove output files
    deps: [clean-server, clean-task, clean-gtk, clean-pkg]
    silent: true
  clean-server:
    internal: true
    cmds:
      - rm m3uetc-server > /dev/null 2>&1
    status:
      - test ! -f ./m3uetc-server
    silent: true
  clean-task:
    internal: true
    cmds:
      - rm m3uetc-task > /dev/null 2>&1
    status:
      - test ! -f ./m3uetc-task
    silent: true
  clean-gtk:
    internal: true
    cmds:
      - rm m3uetc-gtk > /dev/null 2>&1
    status:
      - test ! -f ./m3uetc-gtk
    silent: true
  clean-pkg:
    internal: true
    cmds:
      - rm ./build/m3u-etcetera.deb > /dev/null 2>&1 || exit 0
    silent: true

  convert-icons:
    cmds:
      - |
        set -e
        cd ./data/images
        cp scalable/m3u-etcetera.svg ./m3u-etcetera-logo.svg
        convert 1024x1024/m3u-etcetera.png -resize 150x150 ./m3u-etcetera-logo.png
        for s in 512x512 256x256 128x128 96x96 64x64 48x48 32x32 24x24 16x16
        do
          mkdir -p $s
          convert 1024x1024/m3u-etcetera.png -resize $s $s/m3u-etcetera.png
        done

  copy-cmd-data:
    internal: true
    cmds:
      - task: copy-cmd-data-gtk
    silent: true
  copy-cmd-data-gtk:
    internal: true
    deps: [remove-cmd-data-gtk]
    cmds:
      - cp -r data/ui data/images cmd/m3uetc-gtk/ >/dev/null 2>&1
    silent: true
  remove-cmd-data:
    internal: true
    cmds:
      - task: remove-cmd-data-gtk
    silent: true
  remove-cmd-data-gtk:
    internal: true
    cmds:
      - rm -rf cmd/m3uetc-gtk/ui cmd/m3uetc-gtk/images >/dev/null 2>&1
    status:
      - test ! -d cmd/m3uetc-gtk/ui
      - test ! -d cmd/m3uetc-gtk/images
    ignore_error: true
    silent: true

  bumpy-exists:
    internal: true
    cmds:
      - which bumpy
    silent: true
