# https://taskfile.dev

---
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - task: build:server
      - task: build:task
      - task: build:gtk
  build:s:
    cmds:
      - task: build:server
  build:t:
    cmds:
      - task: build:task
  build:g:
    cmds:
      - task: build:gtk
  build:server:
    cmds:
      - go build -v -o ./m3uetc-server{{exeExt}} ./cmd/m3uetc-server
  build:task:
    cmds:
      - go build -v -o ./m3uetc-task{{exeExt}} ./cmd/m3uetc-task
  build:gtk:
    cmds:
      - go build -v -o ./m3uetc-gtk{{exeExt}} ./cmd/m3uetc-gtk

  clean:
    cmds:
      - rm m3uetc-server > /dev/null 2>&1
      - rm m3uetc-task > /dev/null 2>&1
      - rm m3uetc-gtk > /dev/null 2>&1
    silent: true

  dev:s:
    cmds:
      - task: dev:server
  dev:t:
    cmds:
      - task: dev:task
  dev:g:
    cmds:
      - task: dev:gtk
  dev:server:
    cmds:
      - go run ./cmd/m3uetc-server
    silent: true
  dev:task:
    cmds:
      - go run ./cmd/m3uetc-task
    silent: true
  dev:gtk:
    cmds:
      - go run ./cmd/m3uetc-gtk
    silent: true

  test:
    cmds:
      - go test -v -p 1 ./...
    silent: true

  bump:min:
    cmds:
      - task: bump:minor
    silent: true
  bump:p:
    cmds:
      - task: bump:patch
    silent: true
  bump:minor:
    cmds:
      - bumpy bump --minor
    silent: true
  bump:patch:
    cmds:
      - bumpy bump --patch
    silent: true
  tag:
    cmds:
      - bumpy tag
    silent: true

  proto:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative api/m3uetcpb/*.proto
      - protoc --go-grpc_out=. --go-grpc_opt=paths=source_relative api/m3uetcpb/*.proto
