# https://taskfile.dev

---
version: '3'

vars:
  RACE_FLAG: ''

tasks:
  ## prod build commands
  build:
    desc: Build for production
    deps: [clean]
    cmds:
      - task: build:server
      - task: build:task
      - task: build:gtk
  build:server:
    desc: Build server for production
    aliases:
      - build:s
    cmds:
      - task: build:go
        vars: {SUFFIX: server}
    silent: true
  build:task:
    desc: Build task for production
    aliases:
      - build:t
    cmds:
      - task: build:go
        vars: {SUFFIX: task}
    silent: true
  build:gtk:
    desc: Build gtk for production
    aliases:
      - build:g
    deps: [copy-cmd-data]
    cmds:
      - defer: {task: remove-cmd-data}
      - task: build:go
        vars: {SUFFIX: gtk}
    silent: true
  build:go:
    cmds:
      - >
        go build -ldflags='-s -w' -gcflags=-l -trimpath -o ./m3uetc-{{.SUFFIX}}{{exeExt}}
        ./cmd/m3uetc-{{.SUFFIX}}

  ## dev build commands

  dev:
    desc: Build for development
    cmds:
      - task: dev:server
      - task: dev:task
      - task: dev:gtk
  dev:server:
    desc: Build server for development
    aliases:
      - dev:s
    cmds:
      - task: dev:go
        vars: {SUFFIX: server, RACE_FLAG: "{{.RACE_FLAG}}"}
    silent: true
  dev:task:
    desc: Build task for development
    aliases:
      - dev:t
    cmds:
      - task: dev:go
        vars: {SUFFIX: task, RACE_FLAG: "{{.RACE_FLAG}}"}
    silent: true
  dev:gtk:
    desc: Build gtk for development
    deps: [copy-cmd-data]
    aliases:
      - dev:g
    cmds:
      - defer: {task: remove-cmd-data}
      - task: dev:go
        vars: {SUFFIX: gtk, RACE_FLAG: "{{.RACE_FLAG}}"}
    silent: true
  dev:go: >
    go build -v {{.RACE_FLAG}} -o ./m3uetc-{{.SUFFIX}}{{exeExt}}
    ./cmd/m3uetc-{{.SUFFIX}}

  ## race dev build commands

  race:
    cmds:
      - task: race:server
      - task: race:task
      - task: race:gtk
  race:server:
    aliases:
      - race:s
    cmds:
      - task: dev:server
        vars: {RACE_FLAG: '-race'}
    silent: true
  race:task:
    aliases:
      - race:t
    cmds:
      - task: dev:task
        vars: {RACE_FLAG: '-race'}
    silent: true
  race:gtk:
    aliases:
      - race:g
    cmds:
      - task: dev:gtk
        vars: {RACE_FLAG: '-race'}
    silent: true

  ## semantic version commands

  bump:minor:
    desc: Bump minor version number
    aliases:
      - bump:min
    deps: [bumpy-exists]
    cmds:
      - bumpy bump --minor
  bump:patch:
    desc: Bump patch version number
    deps: [bumpy-exists]
    aliases:
      - bump:p
    cmds:
      - bumpy bump --patch
  tag:
    desc: Create tag for the current ChangeLog
    cmds:
      - bumpy tag

  ## protobuf commands

  proto:
    desc: Process protobuf files
    cmds:
      - >
        protoc --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        api/m3uetcpb/*.proto

  ## utility commands

  clean:
    desc: Clean, remove output files
    deps: [clean-server, clean-task, clean-gtk]
    silent: true
  clean-server:
    cmds:
      - rm m3uetc-server > /dev/null 2>&1
    status:
      - test ! -f ./m3uetc-server
    silent: true
  clean-task:
    cmds:
      - rm m3uetc-task > /dev/null 2>&1
    status:
      - test ! -f ./m3uetc-task
    silent: true
  clean-gtk:
    cmds:
      - rm m3uetc-gtk > /dev/null 2>&1
    status:
      - test ! -f ./m3uetc-gtk
    silent: true
  copy-cmd-data:
    cmds:
      - task: copy-cmd-data-gtk
    silent: true
  copy-cmd-data-gtk:
    deps: [remove-cmd-data-gtk]
    cmds:
      - cp -r data/ui data/images cmd/m3uetc-gtk/ >/dev/null 2>&1
    silent: true
  remove-cmd-data:
    cmds:
      - task: remove-cmd-data-gtk
    silent: true
  remove-cmd-data-gtk:
    cmds:
      - rm -rf cmd/m3uetc-gtk/ui cmd/m3uetc-gtk/images >/dev/null 2>&1
    status:
      - test ! -d cmd/m3uetc-gtk/ui
      - test ! -d cmd/m3uetc-gtk/images
    ignore_error: true
    silent: true
  bumpy-exists:
    cmds:
      - which bumpy
    silent: true
