// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package m3uetcpb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PerspectiveSvcClient is the client API for PerspectiveSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PerspectiveSvcClient interface {
}

type perspectiveSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPerspectiveSvcClient(cc grpc.ClientConnInterface) PerspectiveSvcClient {
	return &perspectiveSvcClient{cc}
}

// PerspectiveSvcServer is the server API for PerspectiveSvc service.
// All implementations must embed UnimplementedPerspectiveSvcServer
// for forward compatibility
type PerspectiveSvcServer interface {
	mustEmbedUnimplementedPerspectiveSvcServer()
}

// UnimplementedPerspectiveSvcServer must be embedded to have forward compatible implementations.
type UnimplementedPerspectiveSvcServer struct {
}

func (UnimplementedPerspectiveSvcServer) mustEmbedUnimplementedPerspectiveSvcServer() {}

// UnsafePerspectiveSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PerspectiveSvcServer will
// result in compilation errors.
type UnsafePerspectiveSvcServer interface {
	mustEmbedUnimplementedPerspectiveSvcServer()
}

func RegisterPerspectiveSvcServer(s grpc.ServiceRegistrar, srv PerspectiveSvcServer) {
	s.RegisterService(&PerspectiveSvc_ServiceDesc, srv)
}

// PerspectiveSvc_ServiceDesc is the grpc.ServiceDesc for PerspectiveSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PerspectiveSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "m3uetcpb.PerspectiveSvc",
	HandlerType: (*PerspectiveSvcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/m3uetcpb/perspective.proto",
}
