// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: api/m3uetcpb/perspective.proto

package m3uetcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Perspective int32

const (
	Perspective_MUSIC      Perspective = 0
	Perspective_RADIO      Perspective = 1
	Perspective_PODCASTS   Perspective = 2
	Perspective_AUDIOBOOKS Perspective = 3
)

// Enum value maps for Perspective.
var (
	Perspective_name = map[int32]string{
		0: "MUSIC",
		1: "RADIO",
		2: "PODCASTS",
		3: "AUDIOBOOKS",
	}
	Perspective_value = map[string]int32{
		"MUSIC":      0,
		"RADIO":      1,
		"PODCASTS":   2,
		"AUDIOBOOKS": 3,
	}
)

func (x Perspective) Enum() *Perspective {
	p := new(Perspective)
	*p = x
	return p
}

func (x Perspective) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Perspective) Descriptor() protoreflect.EnumDescriptor {
	return file_api_m3uetcpb_perspective_proto_enumTypes[0].Descriptor()
}

func (Perspective) Type() protoreflect.EnumType {
	return &file_api_m3uetcpb_perspective_proto_enumTypes[0]
}

func (x Perspective) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Perspective.Descriptor instead.
func (Perspective) EnumDescriptor() ([]byte, []int) {
	return file_api_m3uetcpb_perspective_proto_rawDescGZIP(), []int{0}
}

type PerspectiveDigest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perspective Perspective `protobuf:"varint,1,opt,name=perspective,proto3,enum=m3uetcpb.Perspective" json:"perspective,omitempty"`
	Duration    int64       `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *PerspectiveDigest) Reset() {
	*x = PerspectiveDigest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_m3uetcpb_perspective_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerspectiveDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerspectiveDigest) ProtoMessage() {}

func (x *PerspectiveDigest) ProtoReflect() protoreflect.Message {
	mi := &file_api_m3uetcpb_perspective_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerspectiveDigest.ProtoReflect.Descriptor instead.
func (*PerspectiveDigest) Descriptor() ([]byte, []int) {
	return file_api_m3uetcpb_perspective_proto_rawDescGZIP(), []int{0}
}

func (x *PerspectiveDigest) GetPerspective() Perspective {
	if x != nil {
		return x.Perspective
	}
	return Perspective_MUSIC
}

func (x *PerspectiveDigest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_api_m3uetcpb_perspective_proto protoreflect.FileDescriptor

var file_api_m3uetcpb_perspective_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x33, 0x75, 0x65, 0x74, 0x63, 0x70, 0x62, 0x2f, 0x70,
	0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x33, 0x75, 0x65, 0x74, 0x63, 0x70, 0x62, 0x22, 0x68, 0x0a, 0x11, 0x50, 0x65,
	0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d, 0x33, 0x75, 0x65, 0x74, 0x63, 0x70, 0x62, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0b, 0x70, 0x65, 0x72,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x41, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x53, 0x49, 0x43, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x41, 0x44, 0x49, 0x4f, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x44,
	0x43, 0x41, 0x53, 0x54, 0x53, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x55, 0x44, 0x49, 0x4f,
	0x42, 0x4f, 0x4f, 0x4b, 0x53, 0x10, 0x03, 0x32, 0x10, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x76, 0x63, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6d,
	0x33, 0x75, 0x65, 0x74, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_m3uetcpb_perspective_proto_rawDescOnce sync.Once
	file_api_m3uetcpb_perspective_proto_rawDescData = file_api_m3uetcpb_perspective_proto_rawDesc
)

func file_api_m3uetcpb_perspective_proto_rawDescGZIP() []byte {
	file_api_m3uetcpb_perspective_proto_rawDescOnce.Do(func() {
		file_api_m3uetcpb_perspective_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_m3uetcpb_perspective_proto_rawDescData)
	})
	return file_api_m3uetcpb_perspective_proto_rawDescData
}

var file_api_m3uetcpb_perspective_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_m3uetcpb_perspective_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_m3uetcpb_perspective_proto_goTypes = []interface{}{
	(Perspective)(0),          // 0: m3uetcpb.Perspective
	(*PerspectiveDigest)(nil), // 1: m3uetcpb.PerspectiveDigest
}
var file_api_m3uetcpb_perspective_proto_depIdxs = []int32{
	0, // 0: m3uetcpb.PerspectiveDigest.perspective:type_name -> m3uetcpb.Perspective
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_m3uetcpb_perspective_proto_init() }
func file_api_m3uetcpb_perspective_proto_init() {
	if File_api_m3uetcpb_perspective_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_m3uetcpb_perspective_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerspectiveDigest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_m3uetcpb_perspective_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_m3uetcpb_perspective_proto_goTypes,
		DependencyIndexes: file_api_m3uetcpb_perspective_proto_depIdxs,
		EnumInfos:         file_api_m3uetcpb_perspective_proto_enumTypes,
		MessageInfos:      file_api_m3uetcpb_perspective_proto_msgTypes,
	}.Build()
	File_api_m3uetcpb_perspective_proto = out.File
	file_api_m3uetcpb_perspective_proto_rawDesc = nil
	file_api_m3uetcpb_perspective_proto_goTypes = nil
	file_api_m3uetcpb_perspective_proto_depIdxs = nil
}
