// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package m3uetcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlaybackSvcClient is the client API for PlaybackSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaybackSvcClient interface {
	Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResponse, error)
	ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type playbackSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaybackSvcClient(cc grpc.ClientConnInterface) PlaybackSvcClient {
	return &playbackSvcClient{cc}
}

func (c *playbackSvcClient) Get(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/m3uetcpb.PlaybackSvc/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackSvcClient) ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/m3uetcpb.PlaybackSvc/ExecuteAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybackSvcServer is the server API for PlaybackSvc service.
// All implementations must embed UnimplementedPlaybackSvcServer
// for forward compatibility
type PlaybackSvcServer interface {
	Get(context.Context, *Empty) (*GetResponse, error)
	ExecuteAction(context.Context, *ExecuteActionRequest) (*Empty, error)
	mustEmbedUnimplementedPlaybackSvcServer()
}

// UnimplementedPlaybackSvcServer must be embedded to have forward compatible implementations.
type UnimplementedPlaybackSvcServer struct {
}

func (UnimplementedPlaybackSvcServer) Get(context.Context, *Empty) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPlaybackSvcServer) ExecuteAction(context.Context, *ExecuteActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedPlaybackSvcServer) mustEmbedUnimplementedPlaybackSvcServer() {}

// UnsafePlaybackSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaybackSvcServer will
// result in compilation errors.
type UnsafePlaybackSvcServer interface {
	mustEmbedUnimplementedPlaybackSvcServer()
}

func RegisterPlaybackSvcServer(s grpc.ServiceRegistrar, srv PlaybackSvcServer) {
	s.RegisterService(&PlaybackSvc_ServiceDesc, srv)
}

func _PlaybackSvc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackSvcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3uetcpb.PlaybackSvc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackSvcServer).Get(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackSvc_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackSvcServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m3uetcpb.PlaybackSvc/ExecuteAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackSvcServer).ExecuteAction(ctx, req.(*ExecuteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaybackSvc_ServiceDesc is the grpc.ServiceDesc for PlaybackSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaybackSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "m3uetcpb.PlaybackSvc",
	HandlerType: (*PlaybackSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PlaybackSvc_Get_Handler,
		},
		{
			MethodName: "ExecuteAction",
			Handler:    _PlaybackSvc_ExecuteAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/m3uetcpb/playback.proto",
}
